name: Android BUILD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    
    - name: pull submodules before building
      run: git submodule update --init --recursive

    - name: Grant execute permission for gradlew
      run: chmod +x ./dolphin/Source/Android/gradlew
    - name: Build with Gradle
      run: ./dolphin/Source/Android/gradlew assemble 
