name: Android BUILD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        cmdline-tools-version: 11076708
        accept-android-sdk-licenses: true
    - name: pull submodules before building
      run: git submodule update --init --recursive

    - name: Grant execute permission for gradlew
      run: chmod +x ./Source/Android/gradlew
    - name: Accept the SDK license
      run: sdkmanager --licenses
    - name: Build with Gradle
      run: cd Source/Android && ./gradlew assemble
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.0
      with:
    # Artifact name
        name: artifact # optional, default is artifact
    # A file, directory or wildcard pattern that describes what to upload
        path: Source/Android/app/build/outputs/apk
    # Duration after which artifact will expire in days. 0 means using default retention.
    # The level of compression for Zlib to be applied to the artifact archive. The value can range from 0 to 9: - 0: No compression - 1: Best speed - 6: Default compression (same as GNU Gzip) - 9: Best compression Higher levels will result in better compression, but will take longer to complete. For large files that are not easily compressed, a value of 0 is recommended for significantly faster uploads.

        compression-level: 1 # optional, default is 6
        
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.1.1
      with:
    # The repository owner and the repository name joined together by "/". If github-token is specified, this is the repository that artifacts will be downloaded from.
        repository: ${{ github.repository }} # optional, default is ${{ github.repository }}
    # The id of the workflow run where the desired download artifact was uploaded from. If github-token is specified, this is the run that artifacts will be downloaded from.
        run-id: ${{ github.run_id }}
          
          
